// js/entry_sample.js
// Stand-in for the entry endpoint.
//
//   GET /dictionary_entry/show?dictionary=…&page=…&word=…
//
// One record: the dictionary it came from, the word and the headword it sits
// under, and one panel per language. A panel gives its own heading, the text
// as the dictionary has it, and the line saying what it was taken from. The
// words inside a panel are marked by what they are, so hovering one shows the
// piece of the scan it was read from.
//
// "boxes" are the places on the scan the entry occupies; "concepts" are the
// words several panels share, so that pressing one can list what each panel
// calls it, and "views" are the three ways of looking at the same page.
//
// The reference mock shows a flag beside each language. Flags there come from
// an image CDN, which these pages do not use, so a language is named by its
// code and its own colour instead; the backend can send an icon if it has one.

window.LQ_ENTRY_SAMPLE = {
  "dictionary": "Kamus-ı Türkî",
  "badge": "Kamus-ı Türkî",
  "breadcrumb": [
    {
      "ottoman": "منظر",
      "latin": "manzar"
    },
    {
      "ottoman": "نظر",
      "latin": "nazar"
    }
  ],
  "page": 1417,
  "scan": "../assets/scans/kamus-turki-1417-manzar-slice.png",
  "crops": "../assets/scans/words/",
  "views": [
    {
      "id": "slice",
      "label": {
        "en": "Slice",
        "tr": "Kesit"
      },
      "count": "5"
    },
    {
      "id": "column",
      "label": {
        "en": "Column",
        "tr": "Sütun"
      },
      "count": "3"
    },
    {
      "id": "page",
      "label": {
        "en": "Page",
        "tr": "Sayfa"
      },
      "count": "1417"
    }
  ],
  "notice": {
    "en": "The OCR, transcriptions, transliterations, and translations below were generated by artificial intelligence and may contain errors. Please consult the original Ottoman Turkish text.",
    "tr": "Aşağıdaki OCR, transkripsiyon, transliterasyon ve çeviriler yapay zeka tarafından üretilmiştir; hata içerebilir. Lütfen Osmanlı Türkçesi orijinal metne başvurun."
  },
  "citations": {
    "chicago": "Şemseddin Sami, Kamus-ı Türkî (İstanbul, 1901), 1417.",
    "harvard": "Sami, Ş. (1901) Kamus-ı Türkî. İstanbul, p. 1417.",
    "apa": "Sami, Ş. (1901). Kamus-ı Türkî (p. 1417). İstanbul."
  },
  "tabs": [
    {
      "code": "OTM",
      "flag": "tr",
      "section": "original",
      "title": {
        "en": "Ottoman Turkish",
        "tr": "Osmanlıca"
      }
    },
    {
      "code": "TR",
      "flag": "tr",
      "section": "modern-tr",
      "title": {
        "en": "Modern Turkish",
        "tr": "Modern Türkçe"
      }
    },
    {
      "code": "OCR",
      "flag": "tr",
      "section": "recognized",
      "title": {
        "en": "Recognized Text (OCR)",
        "tr": "Tanınan Metin (OCR)"
      }
    },
    {
      "code": "TRL",
      "flag": "tr",
      "section": "transliteration",
      "title": {
        "en": "Transliteration",
        "tr": "Transliterasyon"
      }
    },
    {
      "code": "AR",
      "flag": "ar",
      "section": "arabic",
      "title": {
        "en": "Arabic",
        "tr": "Arapça"
      }
    },
    {
      "code": "FA",
      "flag": "fa",
      "section": "persian",
      "title": {
        "en": "Persian",
        "tr": "Farsça"
      }
    },
    {
      "code": "EN",
      "flag": "en",
      "section": "english",
      "title": {
        "en": "English",
        "tr": "İngilizce"
      }
    },
    {
      "code": "DE",
      "flag": "de",
      "section": "german",
      "title": {
        "en": "German",
        "tr": "Almanca"
      }
    },
    {
      "code": "FR",
      "flag": "fr",
      "section": "french",
      "title": {
        "en": "French",
        "tr": "Fransızca"
      }
    },
    {
      "code": "IT",
      "flag": "it",
      "section": "italian",
      "title": {
        "en": "Italian",
        "tr": "İtalyanca"
      }
    },
    {
      "code": "ES",
      "flag": "es",
      "section": "spanish",
      "title": {
        "en": "Spanish",
        "tr": "İspanyolca"
      }
    },
    {
      "code": "RU",
      "flag": "ru",
      "section": "russian",
      "title": {
        "en": "Russian",
        "tr": "Rusça"
      }
    },
    {
      "code": "GR",
      "flag": "el",
      "section": "greek",
      "title": {
        "en": "Greek",
        "tr": "Yunanca"
      }
    },
    {
      "code": "HY",
      "flag": "hy",
      "section": "armenian",
      "title": {
        "en": "Armenian",
        "tr": "Ermenice"
      }
    }
  ],
  "sections": [
    {
      "id": "original",
      "flag": "tr",
      "rtl": false,
      "collapsed": false,
      "title": {
        "en": "Ottoman Turkish — Original Image",
        "tr": "Osmanlıca — Orijinal"
      },
      "count": null,
      "panelLabel": {
        "en": "",
        "tr": ""
      },
      "content": {
        "en": "",
        "tr": ""
      },
      "note": {
        "en": "",
        "tr": ""
      },
      "boxes": [
        {
          "kind": "headword",
          "slot": "headword",
          "ottoman": "منظر",
          "latin": "manzar",
          "pair": null
        },
        {
          "kind": "related",
          "slot": "related",
          "ottoman": "نظر",
          "latin": "nazar",
          "pair": null
        },
        {
          "kind": "sub",
          "slot": "sub-1",
          "ottoman": "كريه",
          "latin": "kerîh",
          "pair": "sub"
        },
        {
          "kind": "sub",
          "slot": "sub-2",
          "ottoman": "المنظر",
          "latin": "el-manzar",
          "pair": "sub"
        }
      ]
    },
    {
      "id": "modern-tr",
      "flag": "tr",
      "rtl": false,
      "collapsed": false,
      "title": {
        "en": "Modern Turkish",
        "tr": "Modern Türkçe"
      },
      "count": null,
      "panelLabel": {
        "en": "MODERN TURKISH TRANSCRIPTION",
        "tr": "MODERN TÜRKÇE TRANSKRİPSİYON"
      },
      "content": {
        "en": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>: sz. ar. [<span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>'dan sm.] Görünen yer, görünüş, suret, heyet, lika.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span> = görünüşü çirkin, bed-liḳā.</p>",
        "tr": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>: sz. ar. [<span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>'dan sm.] Görünen yer, görünüş, suret, heyet, lika.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span> = görünüşü çirkin, bed-liḳā.</p>"
      },
      "note": {
        "en": "Şemseddin Sami, <em>Kamus-ı Türkî</em> (İstanbul, 1901), s. 1417.",
        "tr": "Şemseddin Sami, <em>Kamus-ı Türkî</em> (İstanbul, 1901), s. 1417."
      }
    },
    {
      "id": "recognized",
      "flag": "tr",
      "rtl": true,
      "collapsed": true,
      "title": {
        "en": "Recognized Text (OCR)",
        "tr": "Tanınan Metin (OCR)"
      },
      "count": null,
      "panelLabel": {
        "en": "RECOGNIZED TEXT (OCR)",
        "tr": "RECOGNIZED TEXT (OCR)"
      },
      "content": {
        "en": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">منظر</span> سذ. عر. [<span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">نظر</span></span>'دن سم.] كورينن یر، كورينش، صورت، هيئت، لقا.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">كريه المنظر</span> = كورينوشی چركین، بدلقا.</p>",
        "tr": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">منظر</span> سذ. عر. [<span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">نظر</span></span>'دن سم.] كورينن یر، كورينش، صورت، هيئت، لقا.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">كريه المنظر</span> = كورينوشی چركین، بدلقا.</p>"
      },
      "note": {
        "en": "Şemseddin Sami, <em>Kamus-ı Türkî</em> (İstanbul, 1901), s. 1417.",
        "tr": "Şemseddin Sami, <em>Kamus-ı Türkî</em> (İstanbul, 1901), s. 1417."
      }
    },
    {
      "id": "transliteration",
      "flag": "tr",
      "rtl": false,
      "collapsed": true,
      "title": {
        "en": "Transliteration",
        "tr": "Transliterasyon"
      },
      "count": {
        "en": "4 systems",
        "tr": "4 sistem"
      },
      "panelLabel": {
        "en": "TRANSLITERATION 4 systems",
        "tr": "TRANSLITERATION 4 systems"
      },
      "content": {
        "en": "<div class=\"trl-mini-controls\"> <button class=\"trl-mini-btn\">Expand All</button> <div class=\"trl-mini-divider\"></div> <button class=\"trl-mini-btn\">Collapse All</button> </div> <div class=\"trl-systems-indent\"> <div class=\"trl-system\" id=\"trlsys-general-tr\"> <div class=\"trl-system-header\"> <div class=\"trl-system-header-left\"> <div class=\"trl-system-label\">Turkey (General)</div> </div> <button class=\"edit-btn trl-edit-btn\" title=\"Edit\"><span class=\"edit-btn-label\">Edit</span></button> </div> <div class=\"trl-body\"> <div class=\"trl-text\" id=\"trl-general-tr\"> <p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manẓar</span>: sz. Ar. [<span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">naẓar</span></span>'dan sm.] Görünen yer, görünüş, ṣūret, hey'et, liḳā.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span>: Görünüşü çirkin, bed-liḳā.</p>",
        "tr": "<div class=\"trl-mini-controls\"> <button class=\"trl-mini-btn\">Tümünü Aç</button> <div class=\"trl-mini-divider\"></div> <button class=\"trl-mini-btn\">Tümünü Kapat</button> </div> <div class=\"trl-systems-indent\"> <div class=\"trl-system\" id=\"trlsys-general-tr\"> <div class=\"trl-system-header\"> <div class=\"trl-system-header-left\"> <div class=\"trl-system-label\">Türkiye (Genel)</div> </div> <button class=\"edit-btn trl-edit-btn\" title=\"Edit\"><span class=\"edit-btn-label\">Düzenle</span></button> </div> <div class=\"trl-body\"> <div class=\"trl-text\" id=\"trl-general-tr\"> <p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manẓar</span>: sz. Ar. [<span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">naẓar</span></span>'dan sm.] Görünen yer, görünüş, ṣūret, hey'et, liḳā.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span>: Görünüşü çirkin, bed-liḳā.</p>"
      },
      "note": {
        "en": "Şemseddin Sami, <em>Kamus-ı Türkî</em> (İstanbul, 1901), s. 1417.",
        "tr": "Şemseddin Sami, <em>Kamus-ı Türkî</em> (İstanbul, 1901), s. 1417."
      },
      "systems": [
        {
          "id": "general-tr",
          "label": {
            "en": "Turkey (General)",
            "tr": "Türkiye (Genel)"
          },
          "content": {
            "en": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manẓar</span>: sz. Ar. [<span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">naẓar</span></span>'dan sm.] Görünen yer, görünüş, ṣūret, hey'et, liḳā.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span>: Görünüşü çirkin, bed-liḳā.</p>",
            "tr": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manẓar</span>: sz. Ar. [<span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">naẓar</span></span>'dan sm.] Görünen yer, görünüş, ṣūret, hey'et, liḳā.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span>: Görünüşü çirkin, bed-liḳā.</p>"
          }
        },
        {
          "id": "dia",
          "label": {
            "en": "Turkey (DİA)",
            "tr": "Türkiye (DİA)"
          },
          "content": {
            "en": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>: sz. Ar. [<span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>'dan sm.] Görünen yer, görünüş, sûret, hey'et, likā.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerîhü'l-manzar</span>: Görünüşü çirkin, bed-likā.</p>",
            "tr": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>: sz. Ar. [<span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>'dan sm.] Görünen yer, görünüş, sûret, hey'et, likā.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerîhü'l-manzar</span>: Görünüşü çirkin, bed-likā.</p>"
          }
        },
        {
          "id": "brill",
          "label": {
            "en": "BRILL",
            "tr": "BRILL"
          },
          "content": {
            "en": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manẓar</span>: sz. Ar. [<span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">naẓar</span></span>'dan sm.] Görünen yer, görünüş, ṣūra, hayʾa, liqāʾ.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span>: Görünüşü çirkin, bad-liqāʾ.</p>",
            "tr": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manẓar</span>: sz. Ar. [<span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">naẓar</span></span>'dan sm.] Görünen yer, görünüş, ṣūra, hayʾa, liqāʾ.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span>: Görünüşü çirkin, bad-liqāʾ.</p>"
          }
        },
        {
          "id": "ijmes",
          "label": {
            "en": "IJMES",
            "tr": "IJMES"
          },
          "content": {
            "en": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manẓar</span>: sz. Ar. [<span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">naẓar</span></span>'dan sm.] Görünen yer, görünüş, ṣūrat, hayʾat, liqāʾ.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span>: Görünüşü çirkin, bad-liqāʾ.</p>",
            "tr": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manẓar</span>: sz. Ar. [<span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">naẓar</span></span>'dan sm.] Görünen yer, görünüş, ṣūrat, hayʾat, liqāʾ.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span>: Görünüşü çirkin, bad-liqāʾ.</p>"
          }
        }
      ]
    },
    {
      "id": "arabic",
      "flag": "ar",
      "rtl": true,
      "collapsed": true,
      "title": {
        "en": "Arabic Translation",
        "tr": "Arapça Çeviri"
      },
      "count": null,
      "panelLabel": {
        "en": "ترجمة عربية",
        "tr": "ترجمة عربية"
      },
      "content": {
        "en": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">منظر</span>: اسم، عربي [مشتق من <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">نظر</span></span>] المكان الذي يُرى، المظهر، الصورة، الهيئة، الوجه.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">كريه المنظر</span> = قبيح المظهر، سيئ الوجه.</p>",
        "tr": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">منظر</span>: اسم، عربي [مشتق من <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">نظر</span></span>] المكان الذي يُرى، المظهر، الصورة، الهيئة، الوجه.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">كريه المنظر</span> = قبيح المظهر، سيئ الوجه.</p>"
      },
      "note": {
        "en": "ترجمة مستندة إلى: <span dir=\"ltr\">Şemseddin Sami, <em>Kamus-ı Türkî</em> (Istanbul, 1901), p. 1417.</span>",
        "tr": "ترجمة مستندة إلى: <span dir=\"ltr\">Şemseddin Sami, <em>Kamus-ı Türkî</em> (Istanbul, 1901), p. 1417.</span>"
      }
    },
    {
      "id": "persian",
      "flag": "fa",
      "rtl": true,
      "collapsed": true,
      "title": {
        "en": "Persian Translation",
        "tr": "Farsça Çeviri"
      },
      "count": null,
      "panelLabel": {
        "en": "ترجمهٔ فارسی",
        "tr": "ترجمهٔ فارسی"
      },
      "content": {
        "en": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">منظر</span>: اسم، عربی [مشتق از <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">نظر</span></span>] جای دیدنی، ظاهر، صورت، هیئت، چهره.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">کریه‌المنظر</span> = زشت‌رو، بدچهره.</p>",
        "tr": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">منظر</span>: اسم، عربی [مشتق از <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">نظر</span></span>] جای دیدنی، ظاهر، صورت، هیئت، چهره.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">کریه‌المنظر</span> = زشت‌رو، بدچهره.</p>"
      },
      "note": {
        "en": "ترجمه بر اساس: <span dir=\"ltr\">Şemseddin Sami, <em>Kamus-ı Türkî</em> (Istanbul, 1901), p. 1417.</span>",
        "tr": "ترجمه بر اساس: <span dir=\"ltr\">Şemseddin Sami, <em>Kamus-ı Türkî</em> (Istanbul, 1901), p. 1417.</span>"
      }
    },
    {
      "id": "english",
      "flag": "en",
      "rtl": false,
      "collapsed": true,
      "title": {
        "en": "English Translation",
        "tr": "İngilizce Çeviri"
      },
      "count": null,
      "panelLabel": {
        "en": "ENGLISH TRANSLATION",
        "tr": "ENGLISH TRANSLATION"
      },
      "content": {
        "en": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>: n., Arabic [derived from <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>] A place that is seen; appearance, form, aspect, countenance.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span> = ugly in appearance, ill-favored.</p>",
        "tr": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>: n., Arabic [derived from <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>] A place that is seen; appearance, form, aspect, countenance.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span> = ugly in appearance, ill-favored.</p>"
      },
      "note": {
        "en": "Translation based on Şemseddin Sami, <em>Kamus-ı Türkî</em> (Istanbul, 1901), p. 1417.",
        "tr": "Translation based on Şemseddin Sami, <em>Kamus-ı Türkî</em> (Istanbul, 1901), p. 1417."
      }
    },
    {
      "id": "german",
      "flag": "de",
      "rtl": false,
      "collapsed": true,
      "title": {
        "en": "German Translation",
        "tr": "Almanca Çeviri"
      },
      "count": null,
      "panelLabel": {
        "en": "DEUTSCHE ÜBERSETZUNG",
        "tr": "DEUTSCHE ÜBERSETZUNG"
      },
      "content": {
        "en": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>: Subst., arab. [abgeleitet von <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>] Ort, der gesehen wird; Aussehen, Gestalt, Erscheinung, Antlitz.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span> = hässlich von Aussehen, von schlechtem Antlitz.</p>",
        "tr": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>: Subst., arab. [abgeleitet von <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>] Ort, der gesehen wird; Aussehen, Gestalt, Erscheinung, Antlitz.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span> = hässlich von Aussehen, von schlechtem Antlitz.</p>"
      },
      "note": {
        "en": "Übersetzung nach Şemseddin Sami, <em>Kamus-ı Türkî</em> (Istanbul, 1901), S. 1417.",
        "tr": "Übersetzung nach Şemseddin Sami, <em>Kamus-ı Türkî</em> (Istanbul, 1901), S. 1417."
      }
    },
    {
      "id": "french",
      "flag": "fr",
      "rtl": false,
      "collapsed": true,
      "title": {
        "en": "French Translation",
        "tr": "Fransızca Çeviri"
      },
      "count": null,
      "panelLabel": {
        "en": "TRADUCTION FRANÇAISE",
        "tr": "TRADUCTION FRANÇAISE"
      },
      "content": {
        "en": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>: n., arabe [dérivé de <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>] Lieu que l'on voit; apparence, forme, aspect, visage.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span> = laid d'apparence, de mauvaise mine.</p>",
        "tr": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>: n., arabe [dérivé de <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>] Lieu que l'on voit; apparence, forme, aspect, visage.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span> = laid d'apparence, de mauvaise mine.</p>"
      },
      "note": {
        "en": "Traduction d'après Şemseddin Sami, <em>Kamus-ı Türkî</em> (Istanbul, 1901), p. 1417.",
        "tr": "Traduction d'après Şemseddin Sami, <em>Kamus-ı Türkî</em> (Istanbul, 1901), p. 1417."
      }
    },
    {
      "id": "italian",
      "flag": "it",
      "rtl": false,
      "collapsed": true,
      "title": {
        "en": "Italian Translation",
        "tr": "İtalyanca Çeviri"
      },
      "count": null,
      "panelLabel": {
        "en": "TRADUZIONE ITALIANA",
        "tr": "TRADUZIONE ITALIANA"
      },
      "content": {
        "en": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>: s., arabo [derivato da <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>] Luogo che si vede; apparenza, forma, aspetto, volto.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span> = brutto d'aspetto, di brutto viso.</p>",
        "tr": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>: s., arabo [derivato da <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>] Luogo che si vede; apparenza, forma, aspetto, volto.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span> = brutto d'aspetto, di brutto viso.</p>"
      },
      "note": {
        "en": "Traduzione da Şemseddin Sami, <em>Kamus-ı Türkî</em> (Istanbul, 1901), p. 1417.",
        "tr": "Traduzione da Şemseddin Sami, <em>Kamus-ı Türkî</em> (Istanbul, 1901), p. 1417."
      }
    },
    {
      "id": "spanish",
      "flag": "es",
      "rtl": false,
      "collapsed": true,
      "title": {
        "en": "Spanish Translation",
        "tr": "İspanyolca Çeviri"
      },
      "count": null,
      "panelLabel": {
        "en": "TRADUCCIÓN ESPAÑOLA",
        "tr": "TRADUCCIÓN ESPAÑOLA"
      },
      "content": {
        "en": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>: s., árabe [derivado de <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>] Lugar que se ve; apariencia, forma, aspecto, semblante.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span> = feo de apariencia, de mal semblante.</p>",
        "tr": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>: s., árabe [derivado de <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>] Lugar que se ve; apariencia, forma, aspecto, semblante.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span> = feo de apariencia, de mal semblante.</p>"
      },
      "note": {
        "en": "Traducción basada en Şemseddin Sami, <em>Kamus-ı Türkî</em> (Istanbul, 1901), p. 1417.",
        "tr": "Traducción basada en Şemseddin Sami, <em>Kamus-ı Türkî</em> (Istanbul, 1901), p. 1417."
      }
    },
    {
      "id": "russian",
      "flag": "ru",
      "rtl": false,
      "collapsed": true,
      "title": {
        "en": "Russian Translation",
        "tr": "Rusça Çeviri"
      },
      "count": null,
      "panelLabel": {
        "en": "РУССКИЙ ПЕРЕВОД",
        "tr": "РУССКИЙ ПЕРЕВОД"
      },
      "content": {
        "en": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>: сущ., араб. [образовано от <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>] Видимое место; вид, форма, облик, лицо.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span> = безобразный на вид, с неприятным лицом.</p>",
        "tr": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>: сущ., араб. [образовано от <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>] Видимое место; вид, форма, облик, лицо.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span> = безобразный на вид, с неприятным лицом.</p>"
      },
      "note": {
        "en": "Перевод по изданию: Şemseddin Sami, <em>Kamus-ı Türkî</em> (Стамбул, 1901), с. 1417.",
        "tr": "Перевод по изданию: Şemseddin Sami, <em>Kamus-ı Türkî</em> (Стамбул, 1901), с. 1417."
      }
    },
    {
      "id": "greek",
      "flag": "el",
      "rtl": false,
      "collapsed": true,
      "title": {
        "en": "Greek Translation",
        "tr": "Yunanca Çeviri"
      },
      "count": null,
      "panelLabel": {
        "en": "ΕΛΛΗΝΙΚΉ ΜΕΤΆΦΡΑΣΗ Edit",
        "tr": "ΕΛΛΗΝΙΚΉ ΜΕΤΆΦΡΑΣΗ Düzenle"
      },
      "content": {
        "en": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>: ουσ., αραβ. [παράγ. από <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>] Τόπος που βλέπεται· εμφάνιση, μορφή, όψη, πρόσωπο.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span> = άσχημος στην εμφάνιση, δυσειδής.</p>",
        "tr": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>: ουσ., αραβ. [παράγ. από <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>] Τόπος που βλέπεται· εμφάνιση, μορφή, όψη, πρόσωπο.</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span> = άσχημος στην εμφάνιση, δυσειδής.</p>"
      },
      "note": {
        "en": "Translation based on Şemseddin Sami, <em>Kamus-ı Türkî</em> (Istanbul, 1901), p. 1417.",
        "tr": "Translation based on Şemseddin Sami, <em>Kamus-ı Türkî</em> (Istanbul, 1901), p. 1417."
      }
    },
    {
      "id": "armenian",
      "flag": "hy",
      "rtl": false,
      "collapsed": true,
      "title": {
        "en": "Armenian Translation",
        "tr": "Ermenice Çeviri"
      },
      "count": null,
      "panelLabel": {
        "en": "ՀԱՅԵՐԵՆ ԹԱՐԳՄԱՆՈՒԹՅՈՒՆ Edit",
        "tr": "ՀԱՅԵՐԵՆ ԹԱՐԳՄԱՆՈՒԹՅՈՒՆ Düzenle"
      },
      "content": {
        "en": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>. գ., արաբ. [ածանցված <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>-ից] Տեսանելի վայր; արտաքին տեսք, կերպ, դիմագիծ:</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span> = տգեղ արտաքինով, վատ դիմագծով:</p>",
        "tr": "<p><span class=\"entry-word entry-word-headword\" data-img=\"manzar.png\">manzar</span>. գ., արաբ. [ածանցված <span class=\"entry-word entry-word-related\" data-img=\"nazar.png\"><span class=\"entry-hit\">nazar</span></span>-ից] Տեսանելի վայր; արտաքին տեսք, կերպ, դիմագիծ:</p> <p><span class=\"entry-word entry-word-sub\" data-img=\"kerih.png\" data-compound=\"kerih.png,el-manzar.png\">kerīhü'l-manẓar</span> = տգեղ արտաքինով, վատ դիմագծով:</p>"
      },
      "note": {
        "en": "Translation based on Şemseddin Sami, <em>Kamus-ı Türkî</em> (Istanbul, 1901), p. 1417.",
        "tr": "Translation based on Şemseddin Sami, <em>Kamus-ı Türkî</em> (Istanbul, 1901), p. 1417."
      }
    }
  ],
  "concepts": {
    "compound": {
      "rows": [
        {
          "section": "original",
          "target": null,
          "value": null,
          "label": {
            "en": "Original Image",
            "tr": "Orijinal Görsel"
          },
          "prompt": {
            "en": "View corresponding passage",
            "tr": "İlgili bölümü göster"
          }
        },
        {
          "section": "modern-tr",
          "target": null,
          "value": "kerīhü'l-manẓar",
          "label": {
            "en": "Modern Turkish",
            "tr": "Modern Türkçe"
          }
        },
        {
          "section": "recognized",
          "target": null,
          "value": "كريه المنظر",
          "label": {
            "en": "OCR",
            "tr": "OCR"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-general-tr",
          "value": "kerīhü'l-manẓar",
          "label": {
            "en": "Turkey (General)",
            "tr": "Türkiye (Genel)"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-dia",
          "value": "kerîhü'l-manzar",
          "label": {
            "en": "Turkey (DİA)",
            "tr": "Türkiye (DİA)"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-brill",
          "value": "kerīhü'l-manẓar",
          "label": {
            "en": "BRILL",
            "tr": "BRILL"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-ijmes",
          "value": "kerīhü'l-manẓar",
          "label": {
            "en": "IJMES",
            "tr": "IJMES"
          }
        },
        {
          "section": "arabic",
          "target": null,
          "value": "كريه المنظر",
          "label": {
            "en": "Arabic",
            "tr": "Arapça"
          }
        },
        {
          "section": "persian",
          "target": null,
          "value": "کریه‌المنظر",
          "label": {
            "en": "Persian",
            "tr": "Farsça"
          }
        },
        {
          "section": "english",
          "target": null,
          "value": "kerīhü'l-manẓar",
          "label": {
            "en": "English",
            "tr": "İngilizce"
          }
        },
        {
          "section": "german",
          "target": null,
          "value": "kerīhü'l-manẓar",
          "label": {
            "en": "German",
            "tr": "Almanca"
          }
        },
        {
          "section": "french",
          "target": null,
          "value": "kerīhü'l-manẓar",
          "label": {
            "en": "French",
            "tr": "Fransızca"
          }
        },
        {
          "section": "italian",
          "target": null,
          "value": "kerīhü'l-manẓar",
          "label": {
            "en": "Italian",
            "tr": "İtalyanca"
          }
        },
        {
          "section": "spanish",
          "target": null,
          "value": "kerīhü'l-manẓar",
          "label": {
            "en": "Spanish",
            "tr": "İspanyolca"
          }
        },
        {
          "section": "russian",
          "target": null,
          "value": "kerīhü'l-manẓar",
          "label": {
            "en": "Russian",
            "tr": "Rusça"
          }
        },
        {
          "section": "greek",
          "target": null,
          "value": "kerīhü'l-manẓar",
          "label": {
            "en": "Greek",
            "tr": "Yunanca"
          }
        },
        {
          "section": "armenian",
          "target": null,
          "value": "kerīhü'l-manẓar",
          "label": {
            "en": "Armenian",
            "tr": "Ermenice"
          }
        }
      ],
      "rect": {
        "left": 73,
        "top": 49,
        "width": 25,
        "height": 48
      }
    },
    "bad_countenance": {
      "rows": [
        {
          "section": "original",
          "target": null,
          "value": null,
          "label": {
            "en": "Original Image",
            "tr": "Orijinal Görsel"
          },
          "prompt": {
            "en": "View corresponding passage",
            "tr": "İlgili bölümü göster"
          }
        },
        {
          "section": "modern-tr",
          "target": null,
          "value": "bed-liḳā",
          "label": {
            "en": "Modern Turkish",
            "tr": "Modern Türkçe"
          }
        },
        {
          "section": "recognized",
          "target": null,
          "value": "بدلقا",
          "label": {
            "en": "OCR",
            "tr": "OCR"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-general-tr",
          "value": "bed-liḳā",
          "label": {
            "en": "Turkey (General)",
            "tr": "Türkiye (Genel)"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-dia",
          "value": "bed-likā",
          "label": {
            "en": "Turkey (DİA)",
            "tr": "Türkiye (DİA)"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-brill",
          "value": "bad-liqāʾ",
          "label": {
            "en": "BRILL",
            "tr": "BRILL"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-ijmes",
          "value": "bad-liqāʾ",
          "label": {
            "en": "IJMES",
            "tr": "IJMES"
          }
        },
        {
          "section": "arabic",
          "target": null,
          "value": "سيئ الوجه",
          "label": {
            "en": "Arabic",
            "tr": "Arapça"
          }
        },
        {
          "section": "persian",
          "target": null,
          "value": "بدچهره",
          "label": {
            "en": "Persian",
            "tr": "Farsça"
          }
        },
        {
          "section": "english",
          "target": null,
          "value": "ill-favored",
          "label": {
            "en": "English",
            "tr": "İngilizce"
          }
        },
        {
          "section": "german",
          "target": null,
          "value": "von schlechtem Antlitz",
          "label": {
            "en": "German",
            "tr": "Almanca"
          }
        },
        {
          "section": "french",
          "target": null,
          "value": "de mauvaise mine",
          "label": {
            "en": "French",
            "tr": "Fransızca"
          }
        },
        {
          "section": "italian",
          "target": null,
          "value": "di brutto viso",
          "label": {
            "en": "Italian",
            "tr": "İtalyanca"
          }
        },
        {
          "section": "spanish",
          "target": null,
          "value": "de mal semblante",
          "label": {
            "en": "Spanish",
            "tr": "İspanyolca"
          }
        },
        {
          "section": "russian",
          "target": null,
          "value": "с неприятным лицом",
          "label": {
            "en": "Russian",
            "tr": "Rusça"
          }
        },
        {
          "section": "greek",
          "target": null,
          "value": "δυσειδής",
          "label": {
            "en": "Greek",
            "tr": "Yunanca"
          }
        },
        {
          "section": "armenian",
          "target": null,
          "value": "վատ դիմագծով",
          "label": {
            "en": "Armenian",
            "tr": "Ermenice"
          }
        }
      ],
      "rect": {
        "left": 12,
        "top": 78,
        "width": 20,
        "height": 19
      }
    },
    "ugly": {
      "rows": [
        {
          "section": "original",
          "target": null,
          "value": null,
          "label": {
            "en": "Original Image",
            "tr": "Orijinal Görsel"
          },
          "prompt": {
            "en": "View corresponding passage",
            "tr": "İlgili bölümü göster"
          }
        },
        {
          "section": "modern-tr",
          "target": null,
          "value": "çirkin",
          "label": {
            "en": "Modern Turkish",
            "tr": "Modern Türkçe"
          }
        },
        {
          "section": "recognized",
          "target": null,
          "value": "چركین",
          "label": {
            "en": "OCR",
            "tr": "OCR"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-general-tr",
          "value": "çirkin",
          "label": {
            "en": "Turkey (General)",
            "tr": "Türkiye (Genel)"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-dia",
          "value": "çirkin",
          "label": {
            "en": "Turkey (DİA)",
            "tr": "Türkiye (DİA)"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-brill",
          "value": "çirkin",
          "label": {
            "en": "BRILL",
            "tr": "BRILL"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-ijmes",
          "value": "çirkin",
          "label": {
            "en": "IJMES",
            "tr": "IJMES"
          }
        },
        {
          "section": "arabic",
          "target": null,
          "value": "قبيح",
          "label": {
            "en": "Arabic",
            "tr": "Arapça"
          }
        },
        {
          "section": "persian",
          "target": null,
          "value": "زشت‌رو",
          "label": {
            "en": "Persian",
            "tr": "Farsça"
          }
        },
        {
          "section": "english",
          "target": null,
          "value": "ugly",
          "label": {
            "en": "English",
            "tr": "İngilizce"
          }
        },
        {
          "section": "german",
          "target": null,
          "value": "hässlich",
          "label": {
            "en": "German",
            "tr": "Almanca"
          }
        },
        {
          "section": "french",
          "target": null,
          "value": "laid",
          "label": {
            "en": "French",
            "tr": "Fransızca"
          }
        },
        {
          "section": "italian",
          "target": null,
          "value": "brutto",
          "label": {
            "en": "Italian",
            "tr": "İtalyanca"
          }
        },
        {
          "section": "spanish",
          "target": null,
          "value": "feo",
          "label": {
            "en": "Spanish",
            "tr": "İspanyolca"
          }
        },
        {
          "section": "russian",
          "target": null,
          "value": "безобразный",
          "label": {
            "en": "Russian",
            "tr": "Rusça"
          }
        },
        {
          "section": "greek",
          "target": null,
          "value": "άσχημος",
          "label": {
            "en": "Greek",
            "tr": "Yunanca"
          }
        },
        {
          "section": "armenian",
          "target": null,
          "value": "տգեղ",
          "label": {
            "en": "Armenian",
            "tr": "Ermenice"
          }
        }
      ],
      "rect": {
        "left": 33,
        "top": 78,
        "width": 20,
        "height": 19
      }
    },
    "place": {
      "rows": [
        {
          "section": "original",
          "target": null,
          "value": null,
          "label": {
            "en": "Original Image",
            "tr": "Orijinal Görsel"
          },
          "prompt": {
            "en": "View corresponding passage",
            "tr": "İlgili bölümü göster"
          }
        },
        {
          "section": "modern-tr",
          "target": null,
          "value": "Görünen yer",
          "label": {
            "en": "Modern Turkish",
            "tr": "Modern Türkçe"
          }
        },
        {
          "section": "recognized",
          "target": null,
          "value": "كورينن یر",
          "label": {
            "en": "OCR",
            "tr": "OCR"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-general-tr",
          "value": "Görünen yer",
          "label": {
            "en": "Turkey (General)",
            "tr": "Türkiye (Genel)"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-dia",
          "value": "Görünen yer",
          "label": {
            "en": "Turkey (DİA)",
            "tr": "Türkiye (DİA)"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-brill",
          "value": "Görünen yer",
          "label": {
            "en": "BRILL",
            "tr": "BRILL"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-ijmes",
          "value": "Görünen yer",
          "label": {
            "en": "IJMES",
            "tr": "IJMES"
          }
        },
        {
          "section": "arabic",
          "target": null,
          "value": "المكان الذي يُرى",
          "label": {
            "en": "Arabic",
            "tr": "Arapça"
          }
        },
        {
          "section": "persian",
          "target": null,
          "value": "جای دیدنی",
          "label": {
            "en": "Persian",
            "tr": "Farsça"
          }
        },
        {
          "section": "english",
          "target": null,
          "value": "A place that is seen",
          "label": {
            "en": "English",
            "tr": "İngilizce"
          }
        },
        {
          "section": "german",
          "target": null,
          "value": "Ort, der gesehen wird",
          "label": {
            "en": "German",
            "tr": "Almanca"
          }
        },
        {
          "section": "french",
          "target": null,
          "value": "Lieu que l'on voit",
          "label": {
            "en": "French",
            "tr": "Fransızca"
          }
        },
        {
          "section": "italian",
          "target": null,
          "value": "Luogo che si vede",
          "label": {
            "en": "Italian",
            "tr": "İtalyanca"
          }
        },
        {
          "section": "spanish",
          "target": null,
          "value": "Lugar que se ve",
          "label": {
            "en": "Spanish",
            "tr": "İspanyolca"
          }
        },
        {
          "section": "russian",
          "target": null,
          "value": "Видимое место",
          "label": {
            "en": "Russian",
            "tr": "Rusça"
          }
        },
        {
          "section": "greek",
          "target": null,
          "value": "Τόπος που βλέπεται",
          "label": {
            "en": "Greek",
            "tr": "Yunanca"
          }
        },
        {
          "section": "armenian",
          "target": null,
          "value": "Տեսանելի վայր",
          "label": {
            "en": "Armenian",
            "tr": "Ermenice"
          }
        }
      ],
      "rect": {
        "left": 52,
        "top": 26,
        "width": 26,
        "height": 23
      }
    },
    "appearance": {
      "rows": [
        {
          "section": "original",
          "target": null,
          "value": null,
          "label": {
            "en": "Original Image",
            "tr": "Orijinal Görsel"
          },
          "prompt": {
            "en": "View corresponding passage",
            "tr": "İlgili bölümü göster"
          }
        },
        {
          "section": "modern-tr",
          "target": null,
          "value": "görünüş",
          "label": {
            "en": "Modern Turkish",
            "tr": "Modern Türkçe"
          }
        },
        {
          "section": "recognized",
          "target": null,
          "value": "كورينش",
          "label": {
            "en": "OCR",
            "tr": "OCR"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-general-tr",
          "value": "görünüş",
          "label": {
            "en": "Turkey (General)",
            "tr": "Türkiye (Genel)"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-dia",
          "value": "görünüş",
          "label": {
            "en": "Turkey (DİA)",
            "tr": "Türkiye (DİA)"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-brill",
          "value": "görünüş",
          "label": {
            "en": "BRILL",
            "tr": "BRILL"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-ijmes",
          "value": "görünüş",
          "label": {
            "en": "IJMES",
            "tr": "IJMES"
          }
        },
        {
          "section": "arabic",
          "target": null,
          "value": "المظهر",
          "label": {
            "en": "Arabic",
            "tr": "Arapça"
          }
        },
        {
          "section": "persian",
          "target": null,
          "value": "ظاهر",
          "label": {
            "en": "Persian",
            "tr": "Farsça"
          }
        },
        {
          "section": "english",
          "target": null,
          "value": "appearance",
          "label": {
            "en": "English",
            "tr": "İngilizce"
          }
        },
        {
          "section": "german",
          "target": null,
          "value": "Aussehen",
          "label": {
            "en": "German",
            "tr": "Almanca"
          }
        },
        {
          "section": "french",
          "target": null,
          "value": "apparence",
          "label": {
            "en": "French",
            "tr": "Fransızca"
          }
        },
        {
          "section": "italian",
          "target": null,
          "value": "apparenza",
          "label": {
            "en": "Italian",
            "tr": "İtalyanca"
          }
        },
        {
          "section": "spanish",
          "target": null,
          "value": "apariencia",
          "label": {
            "en": "Spanish",
            "tr": "İspanyolca"
          }
        },
        {
          "section": "russian",
          "target": null,
          "value": "вид",
          "label": {
            "en": "Russian",
            "tr": "Rusça"
          }
        },
        {
          "section": "greek",
          "target": null,
          "value": "εμφάνιση",
          "label": {
            "en": "Greek",
            "tr": "Yunanca"
          }
        },
        {
          "section": "armenian",
          "target": null,
          "value": "արտաքին տեսք",
          "label": {
            "en": "Armenian",
            "tr": "Ermenice"
          }
        }
      ],
      "rect": {
        "left": 28,
        "top": 26,
        "width": 24,
        "height": 23
      }
    },
    "form": {
      "rows": [
        {
          "section": "original",
          "target": null,
          "value": null,
          "label": {
            "en": "Original Image",
            "tr": "Orijinal Görsel"
          },
          "prompt": {
            "en": "View corresponding passage",
            "tr": "İlgili bölümü göster"
          }
        },
        {
          "section": "modern-tr",
          "target": null,
          "value": "suret",
          "label": {
            "en": "Modern Turkish",
            "tr": "Modern Türkçe"
          }
        },
        {
          "section": "recognized",
          "target": null,
          "value": "صورت",
          "label": {
            "en": "OCR",
            "tr": "OCR"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-general-tr",
          "value": "ṣūret",
          "label": {
            "en": "Turkey (General)",
            "tr": "Türkiye (Genel)"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-dia",
          "value": "sûret",
          "label": {
            "en": "Turkey (DİA)",
            "tr": "Türkiye (DİA)"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-brill",
          "value": "ṣūra",
          "label": {
            "en": "BRILL",
            "tr": "BRILL"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-ijmes",
          "value": "ṣūrat",
          "label": {
            "en": "IJMES",
            "tr": "IJMES"
          }
        },
        {
          "section": "arabic",
          "target": null,
          "value": "الصورة",
          "label": {
            "en": "Arabic",
            "tr": "Arapça"
          }
        },
        {
          "section": "persian",
          "target": null,
          "value": "صورت",
          "label": {
            "en": "Persian",
            "tr": "Farsça"
          }
        },
        {
          "section": "english",
          "target": null,
          "value": "form",
          "label": {
            "en": "English",
            "tr": "İngilizce"
          }
        },
        {
          "section": "german",
          "target": null,
          "value": "Gestalt",
          "label": {
            "en": "German",
            "tr": "Almanca"
          }
        },
        {
          "section": "french",
          "target": null,
          "value": "forme",
          "label": {
            "en": "French",
            "tr": "Fransızca"
          }
        },
        {
          "section": "italian",
          "target": null,
          "value": "forma",
          "label": {
            "en": "Italian",
            "tr": "İtalyanca"
          }
        },
        {
          "section": "spanish",
          "target": null,
          "value": "forma",
          "label": {
            "en": "Spanish",
            "tr": "İspanyolca"
          }
        },
        {
          "section": "russian",
          "target": null,
          "value": "форма",
          "label": {
            "en": "Russian",
            "tr": "Rusça"
          }
        },
        {
          "section": "greek",
          "target": null,
          "value": "μορφή",
          "label": {
            "en": "Greek",
            "tr": "Yunanca"
          }
        },
        {
          "section": "armenian",
          "target": null,
          "value": "կերպ",
          "label": {
            "en": "Armenian",
            "tr": "Ermenice"
          }
        }
      ],
      "rect": {
        "left": 73,
        "top": 50,
        "width": 17,
        "height": 23
      }
    },
    "aspect": {
      "rows": [
        {
          "section": "original",
          "target": null,
          "value": null,
          "label": {
            "en": "Original Image",
            "tr": "Orijinal Görsel"
          },
          "prompt": {
            "en": "View corresponding passage",
            "tr": "İlgili bölümü göster"
          }
        },
        {
          "section": "modern-tr",
          "target": null,
          "value": "heyet",
          "label": {
            "en": "Modern Turkish",
            "tr": "Modern Türkçe"
          }
        },
        {
          "section": "recognized",
          "target": null,
          "value": "هيئت",
          "label": {
            "en": "OCR",
            "tr": "OCR"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-general-tr",
          "value": "hey'et",
          "label": {
            "en": "Turkey (General)",
            "tr": "Türkiye (Genel)"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-dia",
          "value": "hey'et",
          "label": {
            "en": "Turkey (DİA)",
            "tr": "Türkiye (DİA)"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-brill",
          "value": "hayʾa",
          "label": {
            "en": "BRILL",
            "tr": "BRILL"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-ijmes",
          "value": "hayʾat",
          "label": {
            "en": "IJMES",
            "tr": "IJMES"
          }
        },
        {
          "section": "arabic",
          "target": null,
          "value": "الهيئة",
          "label": {
            "en": "Arabic",
            "tr": "Arapça"
          }
        },
        {
          "section": "persian",
          "target": null,
          "value": "هیئت",
          "label": {
            "en": "Persian",
            "tr": "Farsça"
          }
        },
        {
          "section": "english",
          "target": null,
          "value": "aspect",
          "label": {
            "en": "English",
            "tr": "İngilizce"
          }
        },
        {
          "section": "german",
          "target": null,
          "value": "Erscheinung",
          "label": {
            "en": "German",
            "tr": "Almanca"
          }
        },
        {
          "section": "french",
          "target": null,
          "value": "aspect",
          "label": {
            "en": "French",
            "tr": "Fransızca"
          }
        },
        {
          "section": "italian",
          "target": null,
          "value": "aspetto",
          "label": {
            "en": "Italian",
            "tr": "İtalyanca"
          }
        },
        {
          "section": "spanish",
          "target": null,
          "value": "aspecto",
          "label": {
            "en": "Spanish",
            "tr": "İspanyolca"
          }
        },
        {
          "section": "russian",
          "target": null,
          "value": "облик",
          "label": {
            "en": "Russian",
            "tr": "Rusça"
          }
        },
        {
          "section": "greek",
          "target": null,
          "value": "όψη",
          "label": {
            "en": "Greek",
            "tr": "Yunanca"
          }
        },
        {
          "section": "armenian",
          "target": null,
          "value": "կերպ",
          "label": {
            "en": "Armenian",
            "tr": "Ermenice"
          }
        }
      ],
      "rect": {
        "left": 51,
        "top": 50,
        "width": 19,
        "height": 23
      }
    },
    "countenance": {
      "rows": [
        {
          "section": "original",
          "target": null,
          "value": null,
          "label": {
            "en": "Original Image",
            "tr": "Orijinal Görsel"
          },
          "prompt": {
            "en": "View corresponding passage",
            "tr": "İlgili bölümü göster"
          }
        },
        {
          "section": "modern-tr",
          "target": null,
          "value": "lika",
          "label": {
            "en": "Modern Turkish",
            "tr": "Modern Türkçe"
          }
        },
        {
          "section": "recognized",
          "target": null,
          "value": "لقا",
          "label": {
            "en": "OCR",
            "tr": "OCR"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-general-tr",
          "value": "liḳā",
          "label": {
            "en": "Turkey (General)",
            "tr": "Türkiye (Genel)"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-dia",
          "value": "likā",
          "label": {
            "en": "Turkey (DİA)",
            "tr": "Türkiye (DİA)"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-brill",
          "value": "liqāʾ",
          "label": {
            "en": "BRILL",
            "tr": "BRILL"
          }
        },
        {
          "section": "transliteration",
          "target": "trl-ijmes",
          "value": "liqāʾ",
          "label": {
            "en": "IJMES",
            "tr": "IJMES"
          }
        },
        {
          "section": "arabic",
          "target": null,
          "value": "الوجه",
          "label": {
            "en": "Arabic",
            "tr": "Arapça"
          }
        },
        {
          "section": "persian",
          "target": null,
          "value": "چهره",
          "label": {
            "en": "Persian",
            "tr": "Farsça"
          }
        },
        {
          "section": "english",
          "target": null,
          "value": "countenance",
          "label": {
            "en": "English",
            "tr": "İngilizce"
          }
        },
        {
          "section": "german",
          "target": null,
          "value": "Antlitz",
          "label": {
            "en": "German",
            "tr": "Almanca"
          }
        },
        {
          "section": "french",
          "target": null,
          "value": "visage",
          "label": {
            "en": "French",
            "tr": "Fransızca"
          }
        },
        {
          "section": "italian",
          "target": null,
          "value": "volto",
          "label": {
            "en": "Italian",
            "tr": "İtalyanca"
          }
        },
        {
          "section": "spanish",
          "target": null,
          "value": "semblante",
          "label": {
            "en": "Spanish",
            "tr": "İspanyolca"
          }
        },
        {
          "section": "russian",
          "target": null,
          "value": "лицо",
          "label": {
            "en": "Russian",
            "tr": "Rusça"
          }
        },
        {
          "section": "greek",
          "target": null,
          "value": "πρόσωπο",
          "label": {
            "en": "Greek",
            "tr": "Yunanca"
          }
        },
        {
          "section": "armenian",
          "target": null,
          "value": "դիմագիծ",
          "label": {
            "en": "Armenian",
            "tr": "Ermenice"
          }
        }
      ],
      "rect": {
        "left": 31,
        "top": 50,
        "width": 17,
        "height": 23
      }
    }
  }
};
